function env() {
  return {
   SPREADSHEET_ID : '',
   SHEETNAME_EVENTOS : '',
   SHEETNAME_USER : '',
   SHEETNAME_REFRESH :'',
   PROJECT_FOLDER_ID : '',
   PROJECT_FOLDER_NAME : '',
   PRIVATE_KEY_HASH : '',
   ENV_CRYPTO_KEY_SECRET : '',
   KEY_ACCESS_TOKEN : '',
   KEY_REFRESH_TOKEN : '',
   DOCUMENT_ID_POLITICA_DE_PRIVACIDADE : '',
   DOCUMENT_ID_TERMOS_DE_USO : '',
  }
}